### ISSUE TITLE
Binary Distribution

### ISSUE THREAD

**Issue by jmickey** [breadtubetv/bake#10]
## Binary Distribution

Once we've selected our delivery service (#7), I propose we start providing releases via GitHub Releases, and investigate getting `bake` integrated with Homebrew for easier distribution. The less friction to getting `bake` installed and usable, the better it will be for the overall BreadTubeTV project!

**Comment by dirkkelly** [comment]
Resolved with https://github.com/breadtubetv/bake/pull/20
