### ISSUE TITLE
CI/CD Service

### ISSUE THREAD

**Issue by jmickey** [breadtubetv/bake#7]
## CI/CD Service Discussion

Would like to open up a discussion around which CI/CD service to use now that `bake` has been moved into its own repo.

Personally I've had good experiences with TravisCI and it has a great free offering for open source projects, but I'm hesitant to continue to use and support TravisCI after its acquisition by Idera and the [recent layoffs](https://news.ycombinator.com/item?id=19218036) (forgive the HN link) as a result of that event (although, that could also be a good argument FOR using TravisCI - using their own tool against them).

Some alternatives are: 
- [CircleCI](https://circleci.com) (we use this at work, pretty happy with it)
- [Codeship](http://codeship.com/)
- [SemaphoreCI](https://semaphoreci.com/) (good open source offering)

I imagine there are many more where those came from, but those are the ones I'm most familiar with.

## Binary Distribution

Once we've selected our delivery service, I propose we start providing releases via GitHub Releases, and investigate getting `bake` integrated with Homebrew for easier distribution. The less friction to getting `bake` installed and usable, the better it will be for the overall BreadTubeTV project!

## Poll

- Travis 👍 
- Circle 😄 
- Codeship 🚀 
- Semaphore 🎉

**Comment by dirkkelly** [comment]
We use CircleCI at work and are pretty happy with it, adding a poll to your message.

**Comment by dirkkelly** [comment]
Referenced in #7 by @jaymickey 

> ## Binary Distribution
Once we've selected our delivery service, I propose we start providing releases via GitHub Releases, and investigate getting `bake` integrated with Homebrew for easier distribution. The less friction to getting `bake` installed and usable, the better it will be for the overall BreadTubeTV project!

@jaymickey this is a great idea, suggest chucking it in its own issue (was gonna do it but think it should be made by you)

**Comment by jmickey** [comment]
Closing now that #13 has been merged.
