### ISSUE TITLE
Create an empty videos folder on channel import

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/bake#9]
When importing a channel having the empty videos folder will make it easier for a content dev to add videos, can be merged before importing the videos themselves.

**Comment by jmickey** [comment]
This will also require some sort of file to be within it, otherwise git won't let you track it. I usually do this by creating an empty `.gitkeep` file in the directory, which will allow you to track the folder.

**Comment by dirkkelly** [comment]
Gitkeep is fine. I will be adding a video before commit now that the form requests videos from the submitted. Just a minor PITA to create the folder each time

**Comment by jmickey** [comment]
Resolved in #12
